[supervisord]
nodaemon=true

[program:redis]
command=/usr/bin/redis-server --save "" --appendonly no
autostart=true
autorestart=true
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=2

[program:celery]
command=uv run celery -A nutrition_app.apptasks.celery_instance worker -l info
directory=/app
environment=C_FORCE_ROOT=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600
killasgroup=true
priority=3

[program:app]
command=uv run gunicorn --config gunicorn_config.py flask_app:app
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
