version: '2'
services:
  app:
    build:
      context: .
      args:
        PORT: '80'
        # REDIS_URL: 'redis://10.0.0.3:6379/6'
        REDIS_URL: 'redis://vladh.net:63790/6'
    command: python start_server.py
    ports:
     - '80:80'
     - '8080:8080'
     - '8092:8092'
    volumes:
     - .:/code
