name: Optima Nutrition tests
on: [push,pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
    name: Run tests
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Optima Nutrition
        run: pip install -e .
      - name: Run tests
        working-directory: ./tests
        run: |
          pip install pytest pytest-xdist
          pytest test_tox*.py -n auto --durations=0 --junitxml=test-results.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: './tests/test-results.xml'
